USE [{DATABASE}]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_NC1_{TABLE}_{COLUMN}]   Script Date: {DATE} ******/

CREATE NONCLUSTERED INDEX [IX_NC1_{TABLE}_{COLUMN}] ON  {SCHEMA}.{TABLE}
(
	[{COLUMN}] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO